Drop the outdated date picker snippet
Before, there was an outdated snippet we used to turn an Event's date
field into a date picker. This snippet was no longer necessary; all
browsers had a native date picker in 2023. Also, the snippet
raised the following error that stopped other scripts from running.

> TypeError: element.datepicker is not a function. (In
> 'element.datepicker()', 'element.datepicker' is undefined)

We dropped the outdated, unnecessary JavaScript snippet.

[Trello](https://trello.com/c/9D8OvPuQ)